services:
  wg-chores:
    build:
      context: .
      dockerfile: Dockerfile
    image: wg-chores:latest
    container_name: wg-chores-app
    ports:
      - 8084:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Data Source=/app/data/wgchores.db
    volumes:
      - wgchores-data:/app/data
    restart: unless-stopped
    networks:         # Define the external Traefik network. remove if not using Traefik
      - traefik_proxy

networks:             # Define the external Traefik network. remove if not using Traefik
  traefik_proxy:
    external: true

volumes:
  wgchores-data:
    driver: local
